#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

usage () {
  echo -e "Set MaxStorage Size"
  echo -e "Usage: `basename $0` <size>"
  exit 1
}

if [[ "$1" =~ ^-h$ || "$1" =~ ^--help$ ]]; then
  usage
fi


source "${SCRIPT_DIR}/config/constants"

if [ $# -eq 0 ]; then
  declare -r DETECTED_SIZE_KB=$(df -Pk . | sed 1d | grep -v used | awk '{ print $4 "\t" }')
  echo "Detected size of disk in KB: ${DETECTED_SIZE_KB}"
  declare -r STORAGE_SIZE="$(echo "($DETECTED_SIZE_KB*95/100)" | bc)KB"
else
  declare -r STORAGE_SIZE=$1
fi

echo "Max size to use: ${STORAGE_SIZE}"

cd ${SCRIPT_DIR}
./ipfs-cmd config --json Datastore.StorageMax "\"${STORAGE_SIZE}\""