#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

usage () {
  echo -e "IPFS Server Switch"
  echo -e "Usage: `basename $0` <server-name>"
  exit 1
}

if [ $# -ne 1 ]; then
  usage
fi

echo "declare -r IPFS_SERVER_NAME=$1" > "${SCRIPT_DIR}/config/name"