#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

usage () {
  echo -e "Enable API exposure"
  echo -e "Usage: `basename $0`"
  exit 1
}

if [ $# -ne 0 ]; then
  usage
fi


source "${SCRIPT_DIR}/config/constants"

cd ${SCRIPT_DIR}

./ipfs-cmd config Addresses.API /ip4/0.0.0.0/tcp/5001