#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

usage () {
  echo -e "Unremarkable `basename $0`"
  echo -e "Usage: `basename $0`"
  exit 1
}

if [ $# -ne 0 ]; then
  usage
fi


source "${SCRIPT_DIR}/config/constants"

cd ${SCRIPT_DIR}

./ipfs-cmd config --json Addresses.Swarm '[ "/ip4/0.0.0.0/tcp/4001", "/ip4/127.0.0.1/tcp/4003/ws", "/ip6/::/tcp/4001", "/ip4/0.0.0.0/udp/4001/quic", "/ip6/::/udp/4001/quic" ]'