#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

usage () {
  echo -e "Build Dockerized IPFS"
  echo -e "Usage: `basename $0`"
  exit 1
}

if [ $# -ne 0 ]; then
  usage
fi

source "${SCRIPT_DIR}/config/constants"
declare -r DATE_TAG=$(date +%Y%m%d%H%M%S)

cd "${SCRIPT_DIR}/docker"

# --build-arg "APP_CID=${APP_CID}" \
#  --build-arg "APP_CHECKSUM=${APP_CHECKSUM}" \
#  --build-arg "IPFS_PROXY=${IPFS_PROXY}" \

docker build \
 -t "${IPFS_DOCKER_IMAGE}:${IPFS_DOCKER_TAG}" \
 -t "${IPFS_DOCKER_IMAGE}:${DATE_TAG}" .
