#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

usage () {
  echo -e "IPFS command"
  echo -e "Usage: `basename $0` <ipfs commands....>"
  exit 1
}

if [[ "$1" =~ ^-h$ || "$1" =~ ^--help$ ]]; then
  usage
fi

source "${SCRIPT_DIR}/config/constants"
cd ${SCRIPT_DIR}

mkdir -p ${IPFS_DATA}
mkdir -p ${IPFS_STAGING}

docker run -d --name "${IPFS_SERVER_NAME}" \
  --user $(id -u):$(id -g) \
  -it \
  -v $IPFS_DATA:/data/ipfs:delegated \
  --entrypoint ipfs \
  "${IPFS_DOCKER_IMAGE}:${IPFS_DOCKER_TAG}" \
  init

${SCRIPT_DIR}/ipfs-logs
${SCRIPT_DIR}/ipfs-stop
