#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

usage () {
  echo -e "Unremarkable `basename $0`"
  echo -e "Usage: `basename $0` <server name>"
  exit 1
}

if [ $# -ne 0 ]; then
  usage
fi

source "${SCRIPT_DIR}/config/constants"

docker logs "${IPFS_SERVER_NAME}" -f -t


