#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

usage () {
  echo -e "Build Dockerized IPFS"
  echo -e "Usage: `basename $0`"
  exit 1
}

if [ $# -ne 0 ]; then
  usage
fi

source "${SCRIPT_DIR}/config/constants"
declare -r DATE_TAG=$(date +%Y%m%d%H%M%S)

cd "${SCRIPT_DIR}/docker"

docker build \
 --build-arg "IPFS_VERSION=${IPFS_VERSION}" \
 --build-arg "GO_VERSION=${GO_VERSION}" \
 -t "${IPFS_DOCKER_IMAGE}:${IPFS_DOCKER_TAG}" \
 -t "${IPFS_DOCKER_IMAGE}:${DATE_TAG}" .
