#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

usage () {
  echo -e "Set IPFS announce address"
  echo -e "Usage: `basename $0` <ipfs commands....>"
  exit 1
}

if [[ "$1" =~ ^-h$ || "$1" =~ ^--help$ ]]; then
  usage
fi

source "${SCRIPT_DIR}/config/constants"

IFCONFIG_IP=`ifconfig ${NET_IF} 2>/dev/null | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'`
HOSTNAME_IP=`hostname --ip-address 2>/dev/null| cut -d' ' -f1`
echo "hostname IP: ${HOSTNAME_IP}"
echo "ifconfig IP: ${IFCONFIG_IP}"
PRIMARY_IP=${IFCONFIG_IP}
PRIMARY_IP=${PRIMARY_IP:-$HOSTNAME_IP}
echo "PRIMARY IP: ${PRIMARY_IP}"

declare -r IPFS_ID=$(./ipfs-get-id)
echo "IPFS ID: ${IPFS_ID}"

./ipfs-cmd config --json Addresses.Announce "[ \"/ip4/${PRIMARY_IP}/tcp/${IPFS_SWARM_PORT}/p2p/${IPFS_ID}\" ]"