#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

usage () {
  echo -e "Enable Autorelay"
  echo -e "Usage: `basename $0`"
  exit 1
}

if [ $# -ne 0 ]; then
  usage
fi


source "${SCRIPT_DIR}/config/constants"

cd ${SCRIPT_DIR}

# Experimental. See https://github.com/ipfs/go-ipfs/blob/master/docs/experimental-features.md#autorelay
./ipfs-cmd config --json Swarm.EnableAutoRelay true