#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

usage () {
  echo -e "Create swarm secret"
  echo -e "Usage: `basename $0` <ipfs commands....>"
  exit 1
}

if [[ "$1" =~ ^-h$ || "$1" =~ ^--help$ ]]; then
  usage
fi

source "${SCRIPT_DIR}/config/constants"

echo -e "$(hexdump -n 32 -e '16/1 "%02x"' /dev/urandom)"