#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

usage () {
  echo -e "Get IPFS node ID"
  echo -e "Usage: `basename $0` <file-path>"
  exit 1
}

if [[ "$1" =~ ^-h$ || "$1" =~ ^--help$ ]]; then
  usage
fi

source "${SCRIPT_DIR}/config/constants"

${SCRIPT_DIR}/ipfs-cmd id | jq -r '.ID'