#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

usage () {
  echo -e "Usage: `basename $0`"
  echo -e "Example: ./`basename $0`"
}

if [[ "$1" =~ ^-h$ || "$1" =~ ^--help$ ]]; then
  usage
  exit 1
fi

set -e

# start avahi's dependency
# service dbus start

# start avahi
# service avahi-daemon start
echo "starting avahi...."
avahi-daemon --daemonize --no-drop-root

exec "$@"