#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

usage () {
  echo -e "Usage: `basename $0`"
  echo -e "Example: ./`basename $0`"
}

if [[ "$1" =~ ^-h$ || "$1" =~ ^--help$ ]]; then
  usage
  exit 1
fi

set -e

# MDNS_HOSTNAME="mfoo"
# echo "setting mDNS hostname to ${MDNS_HOSTNAME}"
# TFILE=`mktemp --tmpdir tfile.XXXXX`
# trap "rm -f $TFILE" 0 1 2 3 15
# # sed "s/\(host-name=\).*/\1${MDNS_HOSTNAME}/g"  /etc/avahi/avahi-daemon.conf > "$TFILE"
# sed "s/#host-name=.*/host-name=${MDNS_HOSTNAME}/g"  /etc/avahi/avahi-daemon.conf > "$TFILE"
# cat "$TFILE" > /etc/avahi/avahi-daemon.conf 

# start avahi's dependency
# service dbus start

# start avahi
# service avahi-daemon start
echo "starting avahi...."
avahi-daemon --daemonize --no-drop-root

exec "$@"